name: build arm images

on:
  push:
    branches: arm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build arm64v8
        run: |
            docker buildx build \
            --tag jaywizard/prisma-arm:latest \
            --platform linux/arm64 .
      -
        name: Build arm32v7
        run: |
            docker buildx build \
            --tag jaywizard/prisma-arm:latest \
            --platform linux/arm/v7 -f arm32v7.Dockerfile
