name: build arm images

on:
  push:
    branches: arm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@v2
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      # -
      #   name: Available platforms
      #   run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build arm64
        id: docker_build_arm64
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: jaywizard/prisma-arm:latest
          build-args: |
            ARCH=aarch64
      -
        name: Build arm32v7
        id: docker_build_arm32v7
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: jaywizard/prisma-arm:latest
          build-args: |
            ARCH=armhf